#!/usr/bin/env python3
"""
make_chart.py -- renders the detection results as a matplotlib chart from
evidence/analysis.json. All numbers come from that file, which is itself
generated by harness/analyze_results.py from the raw captures in
evidence/raw/. Nothing here is hand-typed data.

Two panels:
  left:  detection outcome per technique (caught / missed / not applicable)
  right: false positive event counts per probe on pure benign load (log scale,
         since cap_capable is four orders of magnitude noisier than the rest)
"""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Categorical palette slots from the project's dataviz skill reference
# (references/palette.md), light mode.
BLUE = "#2a78d6"
ORANGE = "#eb6834"
GREEN = "#008300"
RED = "#e34948"
GRAY = "#8a8a86"
TEXT_PRIMARY = "#0b0b0b"
TEXT_SECONDARY = "#52514e"
SURFACE = "#fcfcfb"


def main():
    data = json.loads((PROJECT_ROOT / "evidence" / "analysis.json").read_text())
    table = data["detection_results_table"]
    fp = data["false_positive_measurement"]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7), facecolor=SURFACE)
    fig.suptitle("eBPF container-escape detector: what it catches, and how noisy it is",
                 fontsize=13, color=TEXT_PRIMARY, fontweight="bold")

    # --- Left panel: per-technique outcome ---
    labels = []
    colors = []
    values = []
    for row in table:
        label = row["technique"]
        if len(label) > 42:
            label = label[:39] + "..."
        labels.append(label)
        catches = row["detector_catches_it"]
        if catches is True:
            colors.append(GREEN)
            values.append(1)
        elif catches is False:
            colors.append(RED)
            values.append(1)
        else:
            colors.append(GRAY)
            values.append(1)

    y_pos = range(len(labels))
    ax1.barh(y_pos, values, color=colors, height=0.6)
    ax1.set_yticks(list(y_pos))
    ax1.set_yticklabels(labels, fontsize=9, color=TEXT_PRIMARY)
    ax1.invert_yaxis()
    ax1.set_xlim(0, 1.3)
    ax1.set_xticks([])
    ax1.set_facecolor(SURFACE)
    for spine in ("top", "right", "bottom"):
        ax1.spines[spine].set_visible(False)
    ax1.spines["left"].set_color(TEXT_SECONDARY)

    from matplotlib.patches import Patch
    legend_elems = [
        Patch(facecolor=GREEN, label="Detector catches it"),
        Patch(facecolor=RED, label="Detector misses it"),
        Patch(facecolor=GRAY, label="Not applicable / not run on this host"),
    ]
    ax1.legend(handles=legend_elems, loc="lower right", fontsize=8, frameon=False)
    ax1.set_title("Detection outcome by technique", fontsize=11, color=TEXT_PRIMARY, loc="left")

    # --- Right panel: false positives on benign load, log scale ---
    probe_names = ["capability\n(cap_capable)", "namespace\n(unshare/setns)",
                   "mount /\npivot_root", "ptrace", "sensitive\nwrite"]
    probe_values = [
        fp["benign_capability_total_events"],
        fp["benign_namespace_events"],
        fp["benign_mount_events"],
        fp["benign_ptrace_events"],
        fp["benign_sensitive_write_events"],
    ]
    # log scale can't show true zeros; plot zeros as a small marker at 0.5
    # and label them "0" explicitly rather than implying a nonzero value.
    plot_values = [v if v > 0 else 0.5 for v in probe_values]
    bar_colors = [ORANGE if v > 0 else BLUE for v in probe_values]

    bars = ax2.bar(probe_names, plot_values, color=bar_colors, width=0.55)
    ax2.set_yscale("log")
    ax2.set_ylabel("events in 10s of ordinary desktop activity\n(log scale)",
                    fontsize=9, color=TEXT_SECONDARY)
    ax2.set_facecolor(SURFACE)
    for spine in ("top", "right"):
        ax2.spines[spine].set_visible(False)
    ax2.spines["left"].set_color(TEXT_SECONDARY)
    ax2.spines["bottom"].set_color(TEXT_SECONDARY)
    ax2.tick_params(colors=TEXT_SECONDARY, labelsize=8)

    for bar, real_val in zip(bars, probe_values):
        ax2.annotate(f"{real_val:,}", (bar.get_x() + bar.get_width() / 2, bar.get_height()),
                     textcoords="offset points", xytext=(0, 4), ha="center",
                     fontsize=9, color=TEXT_PRIMARY, fontweight="bold")

    ax2.set_title("False positives per probe on benign load (0 relabeled)",
                   fontsize=11, color=TEXT_PRIMARY, loc="left")

    fig.text(0.5, 0.01,
              "Data: evidence/analysis.json, computed from raw bpftrace captures in evidence/raw/. "
              "cap_capable events include known-noisy dev-tool processes (cpptools, gdb) already running on this desktop.",
              ha="center", fontsize=7.5, color=TEXT_SECONDARY, wrap=True)

    plt.tight_layout(rect=(0, 0.04, 1, 0.95))
    out_path = PROJECT_ROOT / "evidence" / "gui" / "04_detection_results_chart.png"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
